<a href="https://colab.research.google.com/github/decadepeng/business-analytics-project/blob/main/Assignment3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Assignment3**

In [4]:
import pandas as pd
import plotly.express as px
import plotly.io as pio
import statsmodels.api as sm
import statsmodels.formula.api as smf
import matplotlib.pyplot as plt
import seaborn as sns
color = sns.color_palette()
import warnings
warnings.filterwarnings("ignore")
%matplotlib inline

In [5]:
country_wise_df = pd.read_csv('country_wise_latest.csv')

In [6]:
country_wise_df.head()

  Country/Region  Confirmed  ...  1 week % increase             WHO Region
0    Afghanistan      36263  ...               2.07  Eastern Mediterranean
1        Albania       4880  ...              17.00                 Europe
2        Algeria      27973  ...              18.07                 Africa
3        Andorra        907  ...               2.60                 Europe
4         Angola        950  ...              26.84                 Africa

[5 rows x 15 columns]

In [7]:
country_wise_df_tidy = country_wise_df[['1 week % increase', 'Deaths / 100 Cases', 'Recovered / 100 Cases']]

In [8]:
country_wise_df_tidy.head()

   1 week % increase  Deaths / 100 Cases  Recovered / 100 Cases
0               2.07                3.50                  69.49
1              17.00                2.95                  56.25
2              18.07                4.16                  67.34
3               2.60                5.73                  88.53
4              26.84                4.32                  25.47

In [9]:
from sklearn.cluster import KMeans
k_means = KMeans(n_clusters=3)
kmeans = k_means.fit(country_wise_df_tidy)
kmeans.cluster_centers_

array([[ 18.22      ,   3.6809589 ,  39.2369863 ],
       [178.97666667,   1.77666667,  20.60333333],
       [  6.10243243,   2.61810811,  82.84081081]])

In [10]:
country_wise_df_tidy['cluster'] = kmeans.labels_
country_wise_df_tidy.head(30)

    1 week % increase  Deaths / 100 Cases  Recovered / 100 Cases  cluster
0                2.07                3.50                  69.49        2
1               17.00                2.95                  56.25        0
2               18.07                4.16                  67.34        2
3                2.60                5.73                  88.53        2
4               26.84                4.32                  25.47        0
5               13.16                3.49                  75.58        2
6               28.02                1.83                  43.35        0
7                6.89                1.90                  71.32        2
8               23.13                1.09                  60.84        0
9                4.13                3.47                  88.75        2
10               9.16                1.39                  76.34        2
11             119.54                2.88                  23.82        1
12               6.89                0.36                  91.46        2
13               9.05                1.31                  55.56        0
14               3.77                6.36                  85.45        2
15               1.57                0.80                  89.95        2
16               3.64               14.79                  26.27        0
17              20.00                4.17                  54.17        0
18              10.49                1.98                  58.53        0
19              10.00                0.00                  86.87        2
20              16.71                3.72                  30.17        0
21              23.81                2.80                  46.96        0
22              41.57                0.27                   8.53        0
23              15.28                3.59                  75.61        2
24               0.00                2.13                  97.87        2
25              18.95                3.27                  52.58        0
26               3.29                4.82                  84.18        2
27               2.64                1.71                  83.43        2
28              17.39                0.26                  79.63        2
29              12.41                0.95                  66.58        2

In [11]:
type(country_wise_df_tidy['cluster'][0])

numpy.int32

In [12]:
country_wise_df_tidy['country'] = country_wise_df['Country/Region']
country_wise_df_tidy.head()

   1 week % increase  Deaths / 100 Cases  ...  cluster      country
0               2.07                3.50  ...        2  Afghanistan
1              17.00                2.95  ...        0      Albania
2              18.07                4.16  ...        2      Algeria
3               2.60                5.73  ...        2      Andorra
4              26.84                4.32  ...        0       Angola

[5 rows x 5 columns]

In [13]:
country_wise_df_tidy
country_wise_3D_plot = px.scatter_3d(
    data_frame = country_wise_df_tidy,
    x = '1 week % increase',
    y = 'Deaths / 100 Cases',
    z = 'Recovered / 100 Cases',
    template = 'ggplot2',
    title = 'Covid Country-wise Analysis',
    color = 'cluster',
    hover_name = 'country',

)

In [14]:
country_wise_3D_plot.show()

In [15]:
# plot text